project_id = "nxomgevljwgqcfssetpj"

[functions.send-auth-email]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.create-restaurant-admin]
verify_jwt = false

[functions.get-admin-emails]
verify_jwt = false

[functions.setup-reseller]
verify_jwt = false

[functions.verify-waiter-pin]
verify_jwt = false

[functions.verify-kitchen-pin]
verify_jwt = false

[functions.mercadopago-create-subscription]
verify_jwt = false

[functions.mercadopago-cancel-subscription]
verify_jwt = false

[functions.mercadopago-landing-checkout]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.lookup-customer-orders]
verify_jwt = false